"""empty message

Revision ID: 135e5fb2ff16
Revises: 
Create Date: 2019-09-22 13:50:59.536476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135e5fb2ff16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('count', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('rules',
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Type', sa.String(length=255), nullable=True),
    sa.Column('Salary', sa.String(length=255), nullable=True),
    sa.Column('Age', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Name')
    )
    op.create_table('workflow',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RelId', sa.String(length=255), nullable=True),
    sa.Column('EntityType', sa.String(length=255), nullable=True),
    sa.Column('DseDsCode', sa.String(length=255), nullable=True),
    sa.Column('OdsStatus', sa.String(length=255), nullable=True),
    sa.Column('GplStatus', sa.String(length=255), nullable=True),
    sa.Column('GblStatus', sa.String(length=255), nullable=True),
    sa.Column('GrlStatus', sa.String(length=255), nullable=True),
    sa.Column('DetStatus', sa.String(length=255), nullable=True),
    sa.Column('GckStatus', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow')
    op.drop_table('rules')
    op.drop_table('config')
    # ### end Alembic commands ###
