"""empty message

Revision ID: 7f77442d3e6d
Revises: 135e5fb2ff16
Create Date: 2019-09-27 00:13:52.858201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f77442d3e6d'
down_revision = '135e5fb2ff16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('count', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('swagger',
    sa.Column('count', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('swagger', sa.String(length=100), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('basePath', sa.String(length=100), nullable=True),
    sa.Column('schemes', sa.JSON(), nullable=True),
    sa.Column('paths', sa.JSON(), nullable=True),
    sa.Column('definitions', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('count')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swagger')
    op.drop_table('menu')
    # ### end Alembic commands ###
